export const banksList = [
  { code: '12', name: 'בנק הפועלים' },
  { code: '10', name: 'בנק לאומי' },
  { code: '11', name: 'בנק דיסקונט' },
  { code: '20', name: 'בנק מזרחי טפחות' },
  { code: '31', name: 'הבנק הבינלאומי' },
  { code: '04', name: 'בנק יהב' },
  { code: '09', name: 'בנק הדואר' },
  { code: '13', name: 'בנק איגוד' },
  { code: '14', name: 'בנק אוצר החייל' },
  { code: '17', name: 'בנק מרכנתיל' },
  { code: '46', name: 'בנק מסד' },
  { code: '52', name: 'בנק פאג"י (פועלי אגודת ישראל)' },
  { code: '26', name: 'יובנק (U-Bank)' },
  { code: '68', name: 'וואן זירו (One Zero)' },
]
